/**
 * Page content registry (generated by npm run import:v2).
 * v2-pages/ remains the editorial archive; these modules are what the app renders.
 */
export { home } from "./home";
export { traurni_uslugi } from "./traurni-uslugi";
export { pogrebenie } from "./pogrebenie";
export { kremaciya } from "./kremaciya";
export { transport_na_pokoinik } from "./transport-na-pokoinik";
export { denonoshtna_pogrebalna_agenciya } from "./denonoshtna-pogrebalna-agenciya";
export { dokumenti_za_pogrebenie } from "./dokumenti-za-pogrebenie";
export { ketaring_pomen } from "./ketaring-pomen";
export { traurni_stoki } from "./traurni-stoki";
export { traurni_venci } from "./traurni-venci";
export { traurni_krastove } from "./traurni-krastove";
export { traurni_kovchezi } from "./traurni-kovchezi";
export { pametnitsi } from "./pametnitsi";
export { ceni } from "./ceni";
export { za_nas } from "./za-nas";
export { kontakti } from "./kontakti";
export { lokacii } from "./lokacii";
export { pogrebalna_agenciya_stamboliyski } from "./pogrebalna-agenciya-stamboliyski";
export { pogrebalna_agenciya_plovdiv } from "./pogrebalna-agenciya-plovdiv";
export { pogrebalna_agenciya_tsalapitsa } from "./pogrebalna-agenciya-tsalapitsa";
export { pogrebalna_agenciya_krichim } from "./pogrebalna-agenciya-krichim";
export { pogrebalna_agenciya_ognyanovo } from "./pogrebalna-agenciya-ognyanovo";
